/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-11-08 02:46:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ums_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>6s-ums</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/plugins/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/plugins/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/style.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html, body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tfont-size: 100%;\r\n");
      out.write("\tfont-family: \"Open Sans\", Helvetica, Arial, sans-serif;\r\n");
      out.write("\tline-height: 1.6;\r\n");
      out.write("\tletter-spacing: 0.06rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body:not() {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section:not (#section-1 ) {\r\n");
      out.write("\tpadding-top: 5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#shade {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground-color: rgba(245, 245, 245, 0.5);\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-1 {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\tbackground-image:\r\n");
      out.write("\t\turl(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/background.png);\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-2 {\r\n");
      out.write("\theight: 40rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-3 {\r\n");
      out.write("\theight: 50rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-4 {\r\n");
      out.write("\theight: 50rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-5 {\r\n");
      out.write("\theight: 50rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-2 img {\r\n");
      out.write("\ttransform: scale(1);\r\n");
      out.write("\ttransition: all .3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-2 img:hover {\r\n");
      out.write("\ttransform: scale(1.1);\r\n");
      out.write("\ttransition: all .3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-4 .system-list-panel .col-md-12 {\r\n");
      out.write("\ttransition: all .3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-4 .system-list-panel .collapsed .fa-plus {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-4 .system-list-panel .collapsed .fa-minus {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-4 .system-list-panel .fa-plus {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-4 .system-list-panel .fa-minus {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section-5 .position-absolute {\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"shade\"></div>\r\n");
      out.write("\t<section id=\"section-1\">\r\n");
      out.write("\t\t<div class=\"container h-100\">\r\n");
      out.write("\t\t\t<div class=\"row h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 offset-lg-1 d-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"align-self-center\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"text-uppercase margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t6s ums <br> <strong>Designed by Follow Traveller</strong>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted m-0\">A man may go faster</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted margin-bottom-20\">But a team gets further\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-lg btn-info u-btn-info col-md-6 click-in\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-send-o\" id=\"1\">&nbsp;进入网站</i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"section-2\">\r\n");
      out.write("\t\t<div class=\"container mt-5 text-center\">\r\n");
      out.write("\t\t\t<h4 class=\"font-size-12\">\r\n");
      out.write("\t\t\t\t<span class=\"u-text-info\">01.</span> 关于我们\r\n");
      out.write("\t\t\t</h4>\r\n");
      out.write("\t\t\t<h2 class=\"margin-bottom-30\">\r\n");
      out.write("\t\t\t\t奋斗中的人儿，<strong>魅力四射</strong>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<p class=\"text-muted\">六只来自遵义医学院的大四狗，正走向优质程序员的进阶之路</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container h-75 pt-4 px-5\">\r\n");
      out.write("\t\t\t<div class=\"row h-100 no-gutters\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-sm-6 u-bg-info text-white overflow-hideen\">\r\n");
      out.write("\t\t\t\t\t<img class=\"w-100\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/section-1-1.png\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 pt-5 px-4\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"mb-4\">一拍即合</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-14\">文老板和组长大人正在开心的讨论项目的Bug，两人似乎一拍即合，立刻就想到了解决方案</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"col-lg-3 col-sm-6 u-bg-darkpurple text-white overflow-hideen\">\r\n");
      out.write("\t\t\t\t\t<img class=\"w-100\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/section-1-2.png\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 pt-5 px-4\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"mb-4\">女中豪杰</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-14\">听说要拍照，李渣渣正襟危坐，俨然一副女中豪杰的样子</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-sm-6 u-bg-pink text-white overflow-hideen\">\r\n");
      out.write("\t\t\t\t\t<img class=\"w-100\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/section-1-3.jpg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 pt-5 px-4\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"mb-4\">志同道合</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-14\">这两位也许正在谈论一些哲学相关的问题</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"col-lg-3 col-sm-6 u-bg-purple text-white overflow-hideen\">\r\n");
      out.write("\t\t\t\t\t<img class=\"w-100\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/section-1-4.jpg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 pt-5 px-4\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"mb-4\">不愿露脸</h3>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-14\">某个不愿露正脸的人，本大大费尽九牛二虎之力也只拍到了一个侧脸，看来不能给同桌开小灶了呢</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"section-3\" class=\"mb-5\">\r\n");
      out.write("\t\t<div class=\"container mt-4 text-center\">\r\n");
      out.write("\t\t\t<h4 class=\"font-size-12\">\r\n");
      out.write("\t\t\t\t<span class=\"u-text-info\">02.</span> 系统简介\r\n");
      out.write("\t\t\t</h4>\r\n");
      out.write("\t\t\t<h2 class=\"margin-bottom-30\">\r\n");
      out.write("\t\t\t\t一个后台的<strong>管理员系统</strong>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<p class=\"text-muted\">在实现基础功能的前提下，添加了注册、找回密码以及上传头像等功能，本系统只供管理员使用，注册成功即成为管理员</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container h-75 pt-4 px-5\">\r\n");
      out.write("\t\t\t<div class=\"row h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 margin-bottom-30 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 h-100 px-4 py-5 bg-light\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-lg m-0 mb-4 fa-leaf u-text-info\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-size-12 font-weight-700 mb-4\">Spring\r\n");
      out.write("\t\t\t\t\t\t\tFramework</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-12 text-muted\">Spring是一个开放源代码的设计层面框架，他解决的是业务逻辑层和其他各层的松耦合问题，因此它将面向接口的编程思想贯穿整个系统应用</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 margin-bottom-30 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 h-100 px-4 py-5 bg-light\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-lg m-0 mb-4 fa-modx u-text-info\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-size-12 font-weight-700 mb-4\">Spring MVC</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-12 text-muted\">Spring 框架提供了构建 Web 应用程序的全功能 MVC 模块。使用 Spring 可插入的 MVC 架构，从而在使用Spring进行WEB开发时，可以选择使用Spring的SpringMVC框架或集成其他MVC开发框架。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 margin-bottom-30 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 h-100 px-4 py-5 bg-light\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-lg m-0 mb-4 fa-slack u-text-info\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-size-12 font-weight-700 mb-4\">Hibernate</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-12 text-muted\">Hibernate是一个开放源代码的对象关系映射框架，它对JDBC进行了非常轻量级的对象封装，是一个全自动的ORM框架</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 margin-bottom-30 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 h-100 px-4 py-5 bg-light\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-lg m-0 mb-4 fa-star u-text-info\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-size-12 font-weight-700 mb-4\">Model View\r\n");
      out.write("\t\t\t\t\t\t\tController</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-12 text-muted\">典型的三层构架体现MVC思想，良好的可扩展性，ssh主流技术有强大的用户社区支持它，所以该框架扩展性非常强</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 margin-bottom-30 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 h-100 px-4 py-5 bg-light\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-lg m-0 mb-4 fa-pagelines u-text-info\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-size-12 font-weight-700 mb-4\">jQuery</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-12 text-muted\">jQuery是一个快速、简洁的JavaScript框架，jQuery设计的宗旨是Write\r\n");
      out.write("\t\t\t\t\t\t\tLess，Do More，即倡导写更少的代码，做更多的事情</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 margin-bottom-30 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 h-100 px-4 py-5 bg-light\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-lg m-0 mb-4 fa-bug u-text-info\"></i>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-size-12 font-weight-700 mb-4\">Bootstrap</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"font-size-12 text-muted\">Bootstrap，来自Twitter，是目前很受欢迎的前端框架。Bootstrap基于HTML、CSS、JavaScript，使得Web开发更加快捷</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"section-4\" class=\"bg-light\">\r\n");
      out.write("\t\t<div class=\"container h-100 px-5\">\r\n");
      out.write("\t\t\t<div class=\"row h-100\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 d-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"align-self-center w-100\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"font-size-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"u-text-info\">03.</span> 功能组成\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"margin-bottom-30\">\r\n");
      out.write("\t\t\t\t\t\t\t多种功能，<strong>纷繁复杂</strong>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">对于一个后端的管理员系统，也值得拥有优美的页面和详尽的功能</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"system-list-panel text-white\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem1Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"col-md-12 u-bg-info p-3 collapsed\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" href=\"#systemItem1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"systemItem1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i><i class=\"fa fa-minus\"></i> 用户管理\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem1\" class=\"collapse col-md-12 u-bg-info pb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"systemItem1Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-parent=\".system-list-panel\">包括增加用户、编辑用户信息、删除单个用户以及删除多个用户等功能</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem2Tab\" class=\"col-md-12 bg-info p-3 collapsed\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tab\" data-toggle=\"collapse\" href=\"#systemItme2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"systemItme2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i><i class=\"fa fa-minus\"></i> 角色管理\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItme2\" class=\"collapse col-md-12 bg-info pb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"systemItem2Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-parent=\".system-list-panel\">包括增加角色、编辑角色信息、删除单个角色以及删除多个角色等功能</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem3Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"col-md-12 u-bg-info p-3 collapsed\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" href=\"#systemItem3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"systemItem3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i><i class=\"fa fa-minus\"></i> 权限管理\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem3\" class=\"collapse col-md-12 u-bg-info pb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"systemItem3Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-parent=\".system-list-panel\">包括增加权限、编辑权限信息、删除单个权限以及删除多个权限等功能</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem4Tab\" class=\"col-md-12 bg-info p-3 collapsed\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tab\" data-toggle=\"collapse\" href=\"#systemItem4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"systemItem4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i><i class=\"fa fa-minus\"></i> 部门管理\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem4\" class=\"collapse col-md-12 bg-info pb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"systemItem4Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-parent=\".system-list-panel\">包括增加部门、编辑部门信息、删除单个部门以及删除多个部门等功能</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem5Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"col-md-12 u-bg-info p-3 collapsed\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" href=\"#systemItem5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"systemItem5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i><i class=\"fa fa-minus\"></i> 上传头像\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem5\" class=\"collapse col-md-12 u-bg-info pb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"systemItem5Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-parent=\".system-list-panel\">注册成功的用户有默认头像，之后可以上传自定义头像</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem6Tab\" class=\"col-md-12 bg-info p-3 collapsed\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tab\" data-toggle=\"collapse\" href=\"#systemItem6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"systemItem6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i><i class=\"fa fa-minus\"></i> 用户注册\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem6\" class=\"collapse col-md-12 bg-info pb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"systemItem6Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-parent=\".system-list-panel\">在系统原型基础上增加用户注册的功能，再登录进系统</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem7Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"col-md-12 u-bg-info p-3 collapsed\" role=\"tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-toggle=\"collapse\" href=\"#systemItem7\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-controls=\"systemItem7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i><i class=\"fa fa-minus\"></i> 找回密码\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"systemItem7\" class=\"collapse col-md-12 u-bg-info pb-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"tabpanel\" aria-labelledby=\"systemItem7Tab\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-parent=\".system-list-panel\">当用户因忘记密码时，可根据注册时的密保问题，进行找回</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"section-5\" class=\"position-relative\">\r\n");
      out.write("\t\t<div class=\"container-fluid h-50\"></div>\r\n");
      out.write("\t\t<div class=\"container-fluid h-50 u-bg-info\"></div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"container-fluid h-100 position-absolute d-flex justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"align-self-center w-75 h-50\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 h-25\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row h-100\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"font-size-12 u-text-info\">项目经理</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>孔立</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">负责登录注册</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"font-size-12 u-text-info\">高级后端开发</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>谢梅</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">负责部门管理</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"font-size-12 u-text-info\">高级前端开发</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>李泽毅</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">负责前端设计编写</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"font-size-12 u-text-info\">高级BUG测试</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>文友</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">负责编写BUG</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"font-size-12 u-text-info\">高级后端开发</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>苏晨光</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">负责权限管理</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"font-size-12 u-text-info\">高级后端开发</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>马泰</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-muted\">负责用户管理</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 h-75 pt-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row h-100 bottom-img\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/people-1.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/people-2.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/people-3.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/people-4.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/people-5.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/people-6.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/plugins/popper/js/popper.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\".click-in\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t/* window.open(\"http://localhost:8080/ums/login\") */\r\n");
      out.write("\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
