/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-09-22 00:47:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/wenyou/Documents/workspace/AjaxStruts/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1505976556000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Struts2-ajax Test</title>\n");
      out.write("<style>\n");
      out.write("#goodsPanel {\n");
      out.write("\twidth: 800px;\n");
      out.write("\theight: 600px;\n");
      out.write("\tborder: 1px solid red;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("\tdisplay: flex;\n");
      out.write("\tflex-direction: row;\n");
      out.write("\tmargin: 0 auto\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-category-panel {\n");
      out.write("\tflex-grow: 1;\n");
      out.write("\tmin-width: 200px;\n");
      out.write("\tmax-width: 200px;\n");
      out.write("\tborder-right: 1px solid red;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-content-panel {\n");
      out.write("\tflex-grow: 1;\n");
      out.write("\tpadding: 0 10px;\n");
      out.write("\toverflow: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-category-panel ul {\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin: 0;\n");
      out.write("\tlist-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-category-panel ul li {\n");
      out.write("\theight: 40px;\n");
      out.write("\tline-height: 40px;\n");
      out.write("\tpadding-left: 30px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tpadding-left: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-category-panel ul li:hover, #goodsPanel .goods-category-panel ul li.active,\n");
      out.write("\t#goodsPanel .goods-content-panel table tbody tr:hover {\n");
      out.write("\tbackground-color: red;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-content-panel table {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-content-panel table thead th {\n");
      out.write("\tborder-bottom: 2px solid #ccc;\n");
      out.write("\tpadding: 5px 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-content-panel table tr td {\n");
      out.write("\tpadding: 5px 10px;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#goodsPanel .goods-content-panel table tbody tr {\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"goodsPanel\">\n");
      out.write("\t\t<div class=\"goods-category-panel\"></div>\n");
      out.write("\t\t<div class=\"goods-content-panel\"></div>\n");
      out.write("\t</div>\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-2.1.3.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\tvar $goodsPanel;\n");
      out.write("\t\tvar $goodsCategoryPanel;\n");
      out.write("\t\tvar $goodsContentPanel;\n");
      out.write("\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t$goodsPanel = $(\"#goodsPanel\");\n");
      out.write("\t\t\t$goodsCategoryPanel = $goodsPanel.find(\".goods-category-panel\");\n");
      out.write("\t\t\t$goodsContentPanel = $goodsPanel.find(\".goods-content-panel\");\n");
      out.write("\n");
      out.write("\t\t\t// 加载商品类别\n");
      out.write("\t\t\t$goodsCategoryPanel.load(\"category\", function() {\n");
      out.write("\t\t\t\tvar $parent = $(this);\n");
      out.write("\n");
      out.write("\t\t\t\t// 点击商品类别\n");
      out.write("\t\t\t\t$parent.find(\".goods-category-item\").on(\"click\", function() {\n");
      out.write("\t\t\t\t\tvar $this = $(this);\n");
      out.write("\t\t\t\t\t// 获取商品类别id\n");
      out.write("\t\t\t\t\tvar categoryId = $this.data(\"id\");\n");
      out.write("\n");
      out.write("\t\t\t\t\t// 高亮处理\n");
      out.write("\t\t\t\t\t$parent.find(\".goods-category-item\").removeClass(\"active\");\n");
      out.write("\t\t\t\t\t$this.addClass(\"active\");\n");
      out.write("\n");
      out.write("\t\t\t\t\t// 加载商品列表\n");
      out.write("\t\t\t\t\t$goodsContentPanel.load(\"goods\", {\n");
      out.write("\t\t\t\t\t\tcategoryId : categoryId\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}).first().click();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
