/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-10-25 10:11:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/Users/wenyou/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1507706400000L));
    _jspx_dependants.put("jar:file:/Users/wenyou/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<!--<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">-->\n");
      out.write("<title>用户管理系统——请登录</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/loginStyle.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/iconfont.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div class=\"htmleaf-container\">\n");
      out.write("\t\t<div class=\"wrapper\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<h1>Welcome</h1>\n");
      out.write("\t\t\t\t<div class=\"group-forms\">\n");
      out.write("\t\t\t\t\t<!-- 注册div -->\n");
      out.write("\t\t\t\t\t<div class=\"view  view-signup \" id=\"1\" data-za-module=\"SignUpForm\">\n");
      out.write("\t\t\t\t\t\t<form class=\"signup-form\" action=\"register\" id=\"sign-form-1\"\n");
      out.write("\t\t\t\t\t\t\tautocomplete=\"off\" method=\"POST\" novalidate=\"novalidate\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-tab-navs\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"navs-slider\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"li1\" onclick=\"signup()\">注册</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"li2\" onclick=\"signin()\">登录</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"group-inputs\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"name input-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input required=\"\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"administrator.administratorId\" aria-label=\"用户名\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmaxlength=\"16\" placeholder=\"用户名\"> <label\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"error is-visible\">请填写姓名</label>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pwd input-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input required=\"\" type=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"administrator.password\" aria-label=\"密码\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"密码（不少于 6 位）\" minlength=\"6\" maxlength=\"16\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tautocomplete=\"off\"> <label class=\"error is-visible\">请填写密码</label>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"question input-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<input required=\"\" type=\"text\" name=\"administrator.question\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"密保问题\" placeholder=\"密保问题\"> <label\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"error is-visible\">请填写密保问题</label>\n");
      out.write("\t\t\t\t\t\t\t\t</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"question input-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"administrator.question\" required\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"请选择密保问题\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"您的生日？？\">您的生日？？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"您父亲/母亲的名字？？\">您父亲/母亲的名字？？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"您父亲/母亲的生日？？\">您父亲/母亲的生日？？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"您小学班主任的名字？？\">您小学班主任的名字？？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"您高中班主任的名字？？\">您高中班主任的名字？？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"answer input-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input required type=\"text\" name=\"administrator.answer\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"密保答案\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"button-wrapper command\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--<input  class=\"sign-button submit\" type=\"button\" name=\"\" id=\"Signup-button\" onclick=\"tosignin()\" value=\"Signup\" />-->\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"sign-button submit\" type=\"submit\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"Signup-button\">Signup</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- 登录div -->\n");
      out.write("\t\t\t\t\t<div class=\"view view-signin \" id=\"2\" data-za-module=\"SignInForm\">\n");
      out.write("\t\t\t\t\t\t<form class=\"signin-form\"\n");
      out.write("\t\t\t\t\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"POST\"\n");
      out.write("\t\t\t\t\t\t\tnovalidate=\"novalidate\" id=\"sign-form-2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"index-tab-navs\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"navs-slider\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"li1\" onclick=\"signup()\">注册</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"li2\" onclick=\"signin()\">登录</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"group-inputs\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"account input-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"administrator.administratorId\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"用户名\" placeholder=\"用户名\" maxlength=\"16\" required=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"error is-visible\">请填写手机号或邮箱</label> <label\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"error is-visible\">账号或密码错误</label>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pwd input-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"administrator.password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"密码\" placeholder=\"密码\" minlength=\"6\" maxlength=\"16\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired=\"\"> <label class=\"error is-visible\">请填写密码</label>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"button-wrapper command\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"sign-button submit\" type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"login-button\">Login</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"signin-misc-wrapper clearfix\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"unable-login\" href=\"toCheckQuestion\">无法登录？</a>\n");
      out.write("\t\t\t\t\t\t\t\t<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<ul class=\"bg-bubbles\">\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"jquery/jquery-3.2.1.min.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\tvar activeForm = \".view-signin\";\n");
      out.write("\t\t$(activeForm).toggleClass(\"active\");\n");
      out.write("\t\tvar activeLi = \".li2\";\n");
      out.write("\t\t$(activeLi).toggleClass(\"selected\");\n");
      out.write("\t\t//登录跳转过度动画\n");
      out.write("\t\t$(\"#login-button\").click(function(event) {\n");
      out.write("\t\t\t$(\".wrapper\").addClass(\"form-success\");\n");
      out.write("\t\t\t$(\".group-forms\").fadeOut(1000, function() {\n");
      out.write("\t\t\t\t$(\"#sign-form-2\").submit();\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t//form标签添加active\n");
      out.write("\t\tfunction toggle(Mid) {\n");
      out.write("\t\t\tif (activeForm != Mid) {\n");
      out.write("\t\t\t\t$(activeForm).toggleClass(\"active\");\n");
      out.write("\t\t\t\t$(Mid).addClass(\"active\");\n");
      out.write("\t\t\t\tactiveForm = Mid;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\t//li标签添加selected\n");
      out.write("\t\tfunction active(Mid) {\n");
      out.write("\t\t\tif (activeLi != Mid) {\n");
      out.write("\t\t\t\t$(activeLi).toggleClass(\"selected\");\n");
      out.write("\t\t\t\t$(Mid).addClass(\"selected\");\n");
      out.write("\t\t\t\tactiveLi = Mid;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tfunction tosignin(ooo) {\n");
      out.write("\t\t\tooo.preventDefault();\n");
      out.write("\t\t\ttoggle(\".view-signin\");\n");
      out.write("\t\t\tactive(\".li2\");\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction signup() {\n");
      out.write("\t\t\ttoggle(\".view-signup\");\n");
      out.write("\t\t\tactive(\".li1\");\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tfunction signin() {\n");
      out.write("\t\t\ttoggle(\".view-signin\");\n");
      out.write("\t\t\tactive(\".li2\");\n");
      out.write("\t\t};\n");
      out.write("\t</script>\n");
      out.write("\t<div class=\"title-panel\">\n");
      out.write("\t\t<span class=\"span-font\" id=\"ifont-1\">6S</span>\n");
      out.write("\t\t<div class=\"title-font\">&nbsp; 用户管理系统</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
