/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-11-22 06:41:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/Users/wenyou/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1507706400000L));
    _jspx_dependants.put("jar:file:/Users/wenyou/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<!--<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">-->\n");
      out.write("<title>用户管理系统——请登录</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/loginStyle.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/iconfont.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div class=\"htmleaf-container\">\n");
      out.write("\t\t<div class=\"wrapper\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<h1>Welcome</h1>\n");
      out.write("\t\t\t\t<div class=\"group-forms\">\n");
      out.write("                    <!-- 注册div -->\n");
      out.write("                    <div class=\"view  view-signup \" id=\"1\" data-za-module=\"SignUpForm\">\n");
      out.write("                        <form class=\"signup-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" id=\"sign-form-1\" autocomplete=\"off\" method=\"POST\" novalidate=\"novalidate\">\n");
      out.write("                            <div class=\"index-tab-navs\">\n");
      out.write("                                <div class=\"navs-slider\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"#\" class=\"li1\" onclick=\"signup()\">注册</a></li>\n");
      out.write("                                        <li><a href=\"#\" class=\"li2\" onclick=\"signin()\">登录</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"group-inputs\">\n");
      out.write("                                <div class=\"name input-wrapper\">\n");
      out.write("                                    <input type=\"text\" name=\"username\" id=\"usernameup\" aria-label=\"用户名\" 　minlength=\"6\" maxlength=\"16\" placeholder=\"用户名（不少于 6 位）\" required>\n");
      out.write("                                    <label class=\"error singupUsernameNullError \">请填写用户名</label>\n");
      out.write("                                    <label class=\"error singupUsernameLessError \">用户名不少于6位</label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"pwd input-wrapper\">\n");
      out.write("                                    <input required type=\"password\" name=\"password\" id=\"passwordup\" aria-label=\"密码\" placeholder=\"密码（不少于 6 位）\" minlength=\"6\" maxlength=\"16\" autocomplete=\"off\">\n");
      out.write("                                    <label class=\"error singupPasswordNullError\">请填写密码</label>\n");
      out.write("                                    <label class=\"error singupPasswordLessError\">密码不少于6位</label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"question input-wrapper\">\n");
      out.write("                                    <select name=\"question\" required placeholder=\"请选择密保问题\">\n");
      out.write("                                    <option value=\"我的生日？\">我的生日？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"我父亲/母亲的名字？\">我父亲/母亲的名字？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"我父亲/母亲的生日？\">我父亲/母亲的生日？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"我小学班主任的名字？\">我小学班主任的名字？</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"我高中班主任的名字？\">我高中班主任的名字？</option>\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"answer input-wrapper\">\n");
      out.write("                                    <input required=\"\" type=\"text\" name=\"answer\" id=\"answer\" aria-label=\"密保答案\"  maxlength=\"16\" placeholder=\"密保答案\">\n");
      out.write("                                    <label class=\"error\">请填写密保答案</label>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"button-wrapper command\">\n");
      out.write("                                <!--<input  class=\"sign-button submit\" type=\"button\" name=\"\" id=\"Signup-button\" onclick=\"tosignin()\" value=\"Signup\" />-->\n");
      out.write("                                <button class=\"sign-button submit\" id=\"Signup-button\"  type=\"submit\">Signup</button>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- 登录div -->\n");
      out.write("                    <div class=\"view view-signin \" id=\"2\" data-za-module=\"SignInForm\">\n");
      out.write("                        <form class=\"signin-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"POST\" novalidate=\"novalidate\" id=\"sign-form-2\">\n");
      out.write("                            <div class=\"index-tab-navs\">\n");
      out.write("                                <div class=\"navs-slider\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"#\" class=\"li1\" onclick=\"signup()\">注册</a></li>\n");
      out.write("                                        <li><a href=\"#\" class=\"li2\" onclick=\"signin()\">登录</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"group-inputs\">\n");
      out.write("                                <div class=\"account input-wrapper\">\n");
      out.write("                                    <input type=\"text\" name=\"username\" id=\"username\" aria-label=\"用户名\" placeholder=\"用户名（不少于 6 位）\" minlength=\"6\"  maxlength=\"16\" required=\"\">\n");
      out.write("                                    <label class=\"error singinUsernameNullError \">请填写用户名</label>\n");
      out.write("                                    <label class=\"error singinUsernameLessError \">用户名不少于6位</label>\n");
      out.write("                                    <label class=\"error extrtip\">请填写用户名或密码</label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"pwd input-wrapper\">\n");
      out.write("                                    <input type=\"password\" name=\"password\" id=\"password\" aria-label=\"密码\" placeholder=\"密码（不少于 6 位）\" minlength=\"6\" maxlength=\"16\" required=\"\">\n");
      out.write("                                    <label class=\"error singinPasswordNullError\">请填写密码</label>\n");
      out.write("                                    <label class=\"error singinPasswordLessError\">密码不少于6位</label>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"button-wrapper command\">\n");
      out.write("                                <button class=\"sign-button submit\" type=\"submit\" id=\"login-button\">Login</button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"signin-misc-wrapper clearfix\">\n");
      out.write("                                <a class=\"unable-login\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toCheckQuestion\">无法登录？</a>\n");
      out.write("                            </div>\n");
      out.write("                            <div style=\"color:red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                             <div style=\"color:green\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<ul class=\"bg-bubbles\">\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t<li></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/jquery/jquery-3.2.1.min.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t// 键盘按下，可被所有键盘按键触发登录\n");
      out.write("\t\t\t$(\"body\").on(\"keydown\", function(event) {\n");
      out.write("\t\t\t\t// 按下回车键\t\t\t\t\n");
      out.write("\t\t\t\tif (event.keyCode === 13) {\n");
      out.write("\t\t\t\t\t$(\"#login-button\").click();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\tvar activeForm = \".view-signin\";\n");
      out.write("\t\t$(activeForm).toggleClass(\"active\");\n");
      out.write("\t\tvar activeLi = \".li2\";\n");
      out.write("\t\t$(activeLi).toggleClass(\"selected\");\n");
      out.write("\t\t//登录跳转过度动画\n");
      out.write("\t\t$(\"#login-button\").click(function(event) {\n");
      out.write("\t\t\t$(\".wrapper\").addClass(\"form-success\");\n");
      out.write("\t\t\t$(\".group-forms\").fadeOut(1000, function() {\n");
      out.write("\t\t\t\t$(\"#sign-form-2\").submit();\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t//form标签添加active\n");
      out.write("\t\tfunction toggle(Mid) {\n");
      out.write("\t\t\tif (activeForm != Mid) {\n");
      out.write("\t\t\t\t$(activeForm).toggleClass(\"active\");\n");
      out.write("\t\t\t\t$(Mid).addClass(\"active\");\n");
      out.write("\t\t\t\tactiveForm = Mid;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\t//li标签添加selected\n");
      out.write("\t\tfunction active(Mid) {\n");
      out.write("\t\t\tif (activeLi != Mid) {\n");
      out.write("\t\t\t\t$(activeLi).toggleClass(\"selected\");\n");
      out.write("\t\t\t\t$(Mid).addClass(\"selected\");\n");
      out.write("\t\t\t\tactiveLi = Mid;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tfunction tosignin(event) {\n");
      out.write("\t\t\tevent.preventDefault();\n");
      out.write("\t\t\ttoggle(\".view-signin\");\n");
      out.write("\t\t\tactive(\".li2\");\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction signup() {\n");
      out.write("\t\t\ttoggle(\".view-signup\");\n");
      out.write("\t\t\tactive(\".li1\");\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\tfunction signin() {\n");
      out.write("\t\t\ttoggle(\".view-signin\");\n");
      out.write("\t\t\tactive(\".li2\");\n");
      out.write("\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\t// 登录验证\n");
      out.write("\t\t   $(\"#username\").blur(function() {\n");
      out.write("\t\t        var $parent = $(this).parent();\n");
      out.write("\t\t        $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t        //进行下一步判断前把之前的结果清除  \n");
      out.write("\t\t        // 登录验证\n");
      out.write("\t\t        if ($(\"#username\").val() == \"\") {\n");
      out.write("\t\t            $parent.find(\"label.singinUsernameNullError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else if ($(\"#username\").val().length < 6) {\n");
      out.write("\t\t            $parent.find(\"label.singinUsernameLessError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t        }\n");
      out.write("\t\t   });\n");
      out.write("\t\t\n");
      out.write("\t\t   $(\"#password\").blur(function() {\n");
      out.write("\t\t\t   var $parent = $(this).parent();\n");
      out.write("\t\t        $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t     // 登录验证\n");
      out.write("\t\t        if ($(\"#password\").val() == \"\") {\n");
      out.write("\t\t            $parent.find(\"label.singinPasswordNullError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else if ($(\"#password\").val().length < 6) {\n");
      out.write("\t\t            $parent.find(\"label.singinPasswordLessError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t        }\n");
      out.write("\t\t   });\n");
      out.write("\n");
      out.write("\n");
      out.write("\t        //注册判断\n");
      out.write("\t        $(\"#usernameup\").blur(function(){\n");
      out.write("\t        \tvar $parent = $(this).parent();\n");
      out.write("\t\t        $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t        \tif ($(\"#usernameup\").val() == \"\") {\n");
      out.write("\t\t            $parent.find(\"label.singupUsernameNullError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else if ($(\"#usernameup\").val().length < 6) {\n");
      out.write("\t\t            $parent.find(\"label.singupUsernameLessError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t        }\t \n");
      out.write("\t        });\n");
      out.write("\t\t        \n");
      out.write("\t\t\t$(\"#passwordup\").blur(function(){\n");
      out.write("\t\t\t\tvar $parent = $(this).parent();\n");
      out.write("\t\t        $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t\t\t//注册判断\n");
      out.write("\t\t        if ($(\"#passwordup\").val() == \"\") {\n");
      out.write("\t\t            $parent.find(\"label.singupPasswordNullError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else if ($(\"#passwordup\").val().length < 6) {\n");
      out.write("\t\t            $parent.find(\"label.singupPasswordLessError\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t        }\n");
      out.write("\t        });\n");
      out.write("\n");
      out.write("\t\t\t$(\"#answer\").blur(function(){\n");
      out.write("\t\t\t\tvar $parent = $(this).parent();\n");
      out.write("\t\t        $parent.find(\"label\").removeClass(\"is-visible\");\n");
      out.write("\t\t\t\t//注册判断\n");
      out.write("\t\t        if ($(\"#answer\").val() == \"\") {\n");
      out.write("\t\t            $parent.find(\"label.error\").addClass(\"is-visible\");\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            $parent.find(\"label.error\").removeClass(\"is-visible\");\n");
      out.write("\t\t        }\n");
      out.write("\t\t\t});\n");
      out.write("\t\t        \n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\t<div class=\"title-panel\">\n");
      out.write("\t\t<span class=\"span-font\" id=\"ifont-1\">6S</span>\n");
      out.write("\t\t<div class=\"title-font\">&nbsp; 用户管理系统</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
