package com.shixun;
// Generated 2017-9-19 11:08:25 by Hibernate Tools 4.3.1.Final

/**
 * HtDbUser generated by hbm2java
 */
public class HtDbUser implements java.io.Serializable {

	private HtDbUserId id;

	public HtDbUser() {
	}

	public HtDbUser(HtDbUserId id) {
		this.id = id;
	}

	public HtDbUserId getId() {
		return this.id;
	}

	public void setId(HtDbUserId id) {
		this.id = id;
	}

}
