package com.shixun;
// Generated 2017-9-19 11:08:25 by Hibernate Tools 4.3.1.Final

/**
 * HtTtUser generated by hbm2java
 */
public class HtTtUser implements java.io.Serializable {

	private HtTtUserId id;

	public HtTtUser() {
	}

	public HtTtUser(HtTtUserId id) {
		this.id = id;
	}

	public HtTtUserId getId() {
		return this.id;
	}

	public void setId(HtTtUserId id) {
		this.id = id;
	}

}
