package com.shixun;
// Generated 2017-9-19 11:08:25 by Hibernate Tools 4.3.1.Final

/**
 * TttUser generated by hbm2java
 */
public class TttUser implements java.io.Serializable {

	private TttUserId id;

	public TttUser() {
	}

	public TttUser(TttUserId id) {
		this.id = id;
	}

	public TttUserId getId() {
		return this.id;
	}

	public void setId(TttUserId id) {
		this.id = id;
	}

	

}
