package com.shixun;
// Generated 2017-9-19 11:08:25 by Hibernate Tools 4.3.1.Final

/**
 * TttUserId generated by hbm2java
 */
public class TttUserId implements java.io.Serializable {

	private String user;
	private Integer balance;

	public TttUserId() {
	}

	public TttUserId(String user, Integer balance) {
		this.user = user;
		this.balance = balance;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TttUserId))
			return false;
		TttUserId castOther = (TttUserId) other;

		return ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
				&& this.getUser().equals(castOther.getUser())))
				&& ((this.getBalance() == castOther.getBalance()) || (this.getBalance() != null
						&& castOther.getBalance() != null && this.getBalance().equals(castOther.getBalance())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		result = 37 * result + (getBalance() == null ? 0 : this.getBalance().hashCode());
		return result;
	}

}
