package com.shixun;
// Generated 2017-9-19 11:08:25 by Hibernate Tools 4.3.1.Final

/**
 * TtUser generated by hbm2java
 */
public class TtUser implements java.io.Serializable {

	private Integer id;
	private String username;
	private String address;
	private Integer balance;

	public TtUser() {
	}

	public TtUser(String username, String address) {
		this.username = username;
		this.address = address;
	}

	public TtUser(String username, String address, Integer balance) {
		this.username = username;
		this.address = address;
		this.balance = balance;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

}
