package com.shixun;
// Generated 2017-9-19 11:08:25 by Hibernate Tools 4.3.1.Final

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private Long id;
	private String username;
	private String password;
	private String repeatPassword;
	private String email;
	private String gender;
	private String profession;
	private String hobby;

	public TUser() {
	}

	public TUser(String username) {
		this.username = username;
	}

	public TUser(String username, String password, String repeatPassword, String email, String gender,
			String profession, String hobby) {
		this.username = username;
		this.password = password;
		this.repeatPassword = repeatPassword;
		this.email = email;
		this.gender = gender;
		this.profession = profession;
		this.hobby = hobby;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRepeatPassword() {
		return this.repeatPassword;
	}

	public void setRepeatPassword(String repeatPassword) {
		this.repeatPassword = repeatPassword;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

}
